name: Build Amrit Kaur APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-pip \
          python3-setuptools \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          libgstreamer1.0-dev \
          libmtdev-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libmysqlclient-dev \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libjpeg-dev \
          libpng-dev \
          libfreetype6-dev \
          liblcms2-dev \
          libblas-dev \
          liblapack-dev \
          libatlas-base-dev \
          gfortran \
          openjdk-17-jdk

        pip install kivy

        # Make a virtual environment
        python -m venv venv
        source venv/bin/activate

        # Build APK
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AmritKaurApp-APK
        path: bin/*.apk
